# Generated by Django 4.2.28 on 2026-03-22 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the storybook', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the story')),
                ('pdf_file', models.FileField(help_text='Upload the PDF storybook file', upload_to='pdfs/')),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cover image for the storybook', null=True, upload_to='covers/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the story was uploaded')),
                ('moral_lesson', models.TextField(blank=True, help_text='AI-generated moral lesson from the story')),
                ('total_pages', models.IntegerField(default=0, help_text='Total number of pages in the PDF')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured story')),
                ('category', models.CharField(blank=True, help_text='Story category (e.g., Fables, Fairy Tales, Adventure)', max_length=100)),
                ('extracted_text', models.TextField(blank=True, help_text='Full text extracted from PDF for text-to-speech')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page', models.IntegerField(default=0)),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='storybook_app.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_read'],
                'unique_together': {('user', 'story')},
            },
        ),
    ]
